#!/bin/bash

cd /mnt/gentoo

wget https://distfiles.gentoo.org/releases/amd64/autobuilds/20250309T170330Z/stage3-amd64-desktop-openrc-20250309T170330Z.tar.xz
tar xpvf stage3-amd64-desktop-openrc-20250309T170330Z.tar.xz


nano -w /mnt/gentoo/etc/portage/make.conf
mirrorselect -i -o >> /mnt/gentoo/etc/portage/make.conf
mkdir --parents /mnt/gentoo/etc/portage/repos.conf
cp /mnt/gentoo/usr/share/portage/config/repos.conf /mnt/gentoo/etc/portage/repos.conf/gentoo.conf
cp --dereference /etc/resolv.conf /mnt/gentoo/etc/
mount --types proc /proc /mnt/gentoo/proc
mount --rbind /sys /mnt/gentoo/sys
mount --make-rslave /mnt/gentoo/sys
mount --rbind /dev /mnt/gentoo/dev
mount --make-rslave /mnt/gentoo/dev
mount --bind /run /mnt/gentoo/run
mount --make-slave /mnt/gentoo/run
echo 'Now, type these commands:
chroot /mnt/gentoo /bin/bash
source /etc/profile
export PS1="(chroot) ${PS1}"
wget https://raw.githubusercontent.com/MartinoDiVietro/Gentoo/main/Gentoo1
chmod +x Gentoo1
./Gentoo1
'















































































